version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./api:/srv/app
      - ./api/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    volumes:
      - ./api/public:/srv/app/public:ro
      - ./api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"

  node:
    build:
      target: app_node_dev
    volumes:
      - ./front:/srv/app
      - /srv/app/node_modules
    ports:
      - "8080:3000"